runtime: nodejs24
env: standard
instance_class: F1
# The first service deployed to a new App Engine app must be `default`.
# Set the service to `default` (or remove this field) so `gcloud app deploy`
# creates the default service on first upload.
service: default

# Cloud SQL instance connection name (PROJECT:REGION:INSTANCE_NAME)
# Set this and the DB_* env vars in deployment or here for quick testing.
beta_settings:
	cloud_sql_instances: "PROJECT:REGION:INSTANCE_NAME"

env_variables:
	DB_USER: 'root'
	DB_PASS: 'REPLACE_WITH_PASSWORD'
	DB_NAME: 'batemanboard'
	INSTANCE_CONNECTION_NAME: 'PROJECT:REGION:INSTANCE_NAME'

# Note: For local development use the Cloud SQL Auth Proxy or set DB_HOST to
# 127.0.0.1 and run a local MySQL instance.
