runtime: custom
env: flex
# The first service deployed to a new App Engine app must be `default`.
# Set the service to `default` (or remove this field) so `gcloud app deploy`
# creates the default service on first upload.
service: default

# Use the Dockerfile in the repository for deployment. App Engine flexible
# will build and run the container using the Dockerfile.
