runtime: nodejs24
env: standard
instance_class: F1

# The first service deployed to a new App Engine app must be `default`.
# Set the service to `default` (or remove this field) so `gcloud app deploy`
# creates the default service on first upload.
service: default

# Replace the placeholder below with your Cloud SQL instance connection name
# Format: PROJECT_ID:REGION:INSTANCE_NAME
beta_settings:
  cloud_sql_instances: "project-fcfa687c-61c0-40b2-a8f:us-central1:free-trial-first-project"

# Environment variables for DB connection. For production, prefer Secret Manager
# and reference secrets through the Cloud Console rather than storing them here.
env_variables:
  DB_USER: "root"
  DB_PASS: "fappah"
  DB_NAME: "batemanboard"
  INSTANCE_CONNECTION_NAME: "project-fcfa687c-61c0-40b2-a8f:us-central1:free-trial-first-project"

# Local dev notes:
# - To develop locally with Cloud SQL, run the Cloud SQL Auth Proxy and set
#   DB_HOST=127.0.0.1 and DB_PORT=3306 in your environment.
# - If you deploy to App Engine Flexible or use a private IP for your Cloud SQL
#   instance, use DB_HOST and DB_PORT instead of the Unix socket.
# Security notes:
# - Grant the App Engine default service account the "Cloud SQL Client" role.
# - Store DB credentials in Secret Manager and load them via runtime config
#   or the Cloud Console instead of committing them to source control.
