steps:
  # Step 1: Install dependencies
  - name: 'node:24'
    entrypoint: npm
    args: ['ci']
    
  # Step 2: Run tests (optional - adjust based on your testing setup)
  - name: 'node:24'
    entrypoint: npm
    args: ['test']
    
  # Step 3: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$SHORT_SHA', '-t', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest', '.']
      
  # Step 4: Push image to Container Registry Using Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$SHORT_SHA']
      
  # Step 5: Deploy to Cloud Run (optional)
  - name: 'gcr.io/cloud-builders/run'
    args: ['deploy', '${_SERVICE_NAME}', '--image', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$SHORT_SHA', '--region', '${_REGION}', '--platform', 'managed', '--allow-unauthenticated']

images:
  - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:latest'

substitutions:
  _SERVICE_NAME: 'bateman-music-board'
  _REGION: 'us-central1'

options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: '3600s'
