steps:
  # Step 1: Install dependencies
  - name: 'node:24'
    entrypoint: npm
    args: ['ci']
    
  # Step 2: Run tests (optional - adjust based on your testing setup)
  - name: 'node:24'
    entrypoint: npm
    args: ['test']
    
  # Step 3: Deploy to App Engine (uses the repo's Dockerfile because app.yaml
  # specifies a custom runtime with flexible environment).
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args: ['-c', 'gcloud app deploy app.yaml --project=$PROJECT_ID --version=$SHORT_SHA --quiet']

substitutions:
  _SERVICE_NAME: 'bateman-music-board'
  _REGION: 'us-central1'

options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: '3600s'
